version: '2'

services:
  test:
    build: .
    environment:
      - SAUCE_USERNAME
      - SAUCE_ACCESS_KEY
      - SAUCE_SERVER
      - SAUCE_ENDPOINT
      - SAUCE_PLATFORM
      - SAUCE_BROWSER
      - SAUCE_BROWSER_VERSION
